Set flexGrow on tooltip wrappers
airplanedev/views pull request #114
Opened 2023-10-06 06:59 UTC by geodn

## Description
Task-backed buttons currently have tooltips with div wrappers. The issue is that the div wrapper prevents width and height props from being properly applied to task-backed buttons. Adding flexGrow fixes the issue by preventing the div wrapper from constricting the size of the Tooltip contents. 
## Test plan
Chromatic shows no regressions
Tested a view with the following components. Button is cut off before the change, and takes up 2/3 of the screen width after the change.
```
<Stack direction="row" width="full">
  <Button task="list_accounts" width="2/3">
    Click Me
  </Button>
</Stack>
```

2023-10-06 07:07 UTC, geodn commented on lib/src/components/form/Form.tsx
> +          <div>
Need to wrap everything in a div for justify-end to have the desired effect, because the Tooltip now grows to fit the parent container.

2023-10-18 17:29 UTC, leeweisberger requested changes
Can we just remove the wrapper div? I feel like that will just fix our problems?

2023-10-18 17:29 UTC, leeweisberger commented on lib/src/components/form/Form.tsx
> +          <div>
I think it's incorrect to add styling like flex-grow to the underlying component because you then have to do things like this.

In the same way, this example which I would expect to place the button at the end, doesn't and I would have to wrap it in a div.

<img width="319" alt="image" src="https://github.com/airplanedev/views/assets/6363419/cbc9fb9d-84cb-401c-bbf3-5bb09619e2aa">

2023-10-18 17:29 UTC, leeweisberger commented on lib/src/components/tooltip/Tooltip.tsx
> +        ? createElement(wrapper, { style: { flexGrow: 1 } }, children)
Instead of adding style to the element (we're still going to have bugs where buttons behave differently if they're task-backed vs not, just a different bug), can we just remove the wrapper from the tooltip? Everything seems to work if the tooltip doesn't wrap things in a div and uses the button element directly. I'm not sure why we added that in this pr:
https://github.com/airplanedev/views-private/commit/57766d8c2d7914055aa2c514070fcd9d3592b1e6

2023-10-18 17:29 UTC, leeweisberger commented on lib/src/components/form/Form.tsx
> +          <div>
i.e. this fixes one bug but introduces another

2023-10-26 19:17 UTC, geodn commented on lib/src/components/tooltip/Tooltip.tsx
> +        ? createElement(wrapper, { style: { flexGrow: 1 } }, children)
Ended up removing the wrapper, as discussed

2023-10-26 20:21 UTC, leeweisberger approved these changes

2023-10-26 21:48 UTC, merged